'use client';
import {useState,useEffect} from 'react';
import {flushSync} from 'react-dom';
import {UtensilsCrossed, Plus, Minus, ShoppingBag, ReceiptText, ArrowRight, Check, Leaf, Flame, Image as ImageIcon} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
type Dish={id:number;name:string;prices:number[];pending?:boolean};
const raw:[string, [string,number[],boolean?][]][]=[
['大盘系列', [['大盘鸡',[68,108]],['辣子鸡',[68,98]],['大盘鱼',[58,88]],['大盘牛 / 羊肚',[88,118]],['红烧羊排',[88,118]],['土豆烧牛腩',[68,108]],['香辣锅',[68]]]],
['拌面系列', [['纯羊肉拌面',[28]],['老牌过油肉',[22]],['辣子肉拌面',[18]],['伊犁碎肉拌面',[18]],['干煸炒面',[18]],['土豆丝拌面',[16]],['西辣蛋拌面',[16]],['茄子辣子肉拌面',[16]],['毛白菜拌面',[16]],['毛芹菜拌面',[16]],['蘑菇拌面',[18],true],['哨子面 / 肉丝面',[16]]]],
['小炒系列', [['水煮牛肉片',[32]],['香辣口水鸡',[28]],['脆椒鸡丁',[28]],['泡椒番茄鱼片',[28]],['小炒黄牛肉',[28]],['夹沙烧牛肉丸',[26],true],['干锅土豆片',[20]],['锅包肉烧番茄',[20],true],['干锅茄片',[18]],['青椒肉丝',[18]],['干丝香芹菇',[16],true],['辣椒烧茄子',[16]],['干锅豆角',[18],true]]],
['素菜系列', [['蒜蓉油麦菜',[12]],['炝炒生菜',[12]],['酸辣土豆丝',[12]],['韭菜银芽炒蛋',[12],true],['三色烩木耳',[12]],['家常豆腐',[12]]]],
['凉菜系列', [['拌牛肉',[20],true],['拌鸡丝',[16]],['蒜蓉菠菜',[12]],['盐水花生米',[12]],['皮辣红',[12]],['拌三丝',[12]],['拌苦瓜',[12]],['拌黄瓜',[12]]]],
['职工套餐', [['碎肉抓饭',[18]],['两荤一素 + 汤',[16]]]]
];
let next=0;const menu=raw.map(([name,items])=>({name,items:items.map(([name,prices,pending])=>({id:next++,name,prices,pending}))}));
type Line={dish:Dish;size:number;qty:number};type Order={id:number;items:Line[];note:string;total:number};
export default function Home(){
 const [category,setCategory]=useState(0),[cart,setCart]=useState<Line[]>([]),[orders,setOrders]=useState<Order[]>([]),[note,setNote]=useState(''),[panel,setPanel]=useState<'cart'|'orders'|'source'|null>(null),[selected,setSelected]=useState<Dish|null>(null),[size,setSize]=useState(0),[message,setMessage]=useState('');
 const total=cart.reduce((s,l)=>s+l.dish.prices[l.size]*l.qty,0),count=cart.reduce((s,l)=>s+l.qty,0);
 function add(dish:Dish,size=0){setCart(prev=>{const found=prev.find(l=>l.dish.id===dish.id&&l.size===size);return found?prev.map(l=>l===found?{...l,qty:l.qty+1}:l):[...prev,{dish,size,qty:1}]});setMessage(`已添加 ${dish.name}`);}
 useEffect(()=>{
 const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void|Promise<void>}}).modelContext;
 if(!context?.registerTool)return;
 const lifecycle=new AbortController();
 const tool={name:'stage_menu_items',title:'选择演示菜品',description:'按菜品名称批量添加到当前购物车；不提交订单。',inputSchema:{type:'object',properties:{items:{type:'array',minItems:1,maxItems:20,items:{type:'object',properties:{name:{type:'string'},size:{type:'integer',minimum:0,maximum:1}},required:['name'],additionalProperties:false}}},required:['items'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){
 const items=(input as {items?:{name:string;size?:number}[]})?.items;
 if(!Array.isArray(items)||!items.length||items.length>20)throw new Error('需要 1 至 20 项菜品');
 const resolved=items.map(item=>{const dish=menu.flatMap(c=>c.items).find(d=>d.name===item?.name);const size=item?.size??0;if(!dish||!Number.isInteger(size)||size<0||size>=dish.prices.length)throw new Error('菜品或份量无效');return {dish,size}});
 flushSync(()=>resolved.forEach(({dish,size})=>add(dish,size)));
 return {added:resolved.map(({dish,size})=>({name:dish.name,price:dish.prices[size]})),submitted:false};
 }};
 try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}
 return ()=>lifecycle.abort();
 },[]);
 function change(id:number,size:number,delta:number){setCart(prev=>prev.map(l=>l.dish.id===id&&l.size===size?{...l,qty:l.qty+delta}:l).filter(l=>l.qty>0));}
 function submit(){if(!cart.length)return;setOrders(prev=>[...prev,{id:prev.length+1,items:cart.map(l=>({...l})),note,total}]);setCart([]);setNote('');setPanel('orders');setMessage('演示订单已提交');}
 return <div className="app-shell">
 <header className="topbar"><div className="brand"><span className="brand-icon"><UtensilsCrossed size={22}/></span><div><strong>桌边点餐</strong><small>堂食 · 扫码即点</small></div></div><button className="quiet" onClick={()=>setPanel('orders')}><ReceiptText size={18}/>本桌订单{orders.length>0&&<span className="pill">{orders.length}</span>}</button></header>
 <div className="demo-banner">试用演示 · 餐后结账 · 不会产生真实订单或扣款</div>
 <main><section className="welcome"><div><div className="eyebrow">欢迎入座 · 慢慢挑，热热吃</div><h1>今天，吃点什么？</h1><p>大盘好菜，现点现做。</p></div><div className="table-badge"><span>当前桌号</span><strong>01<span>桌</span></strong><small>演示桌位</small></div></section>
 <div className="workspace"><aside className="categories" aria-label="菜品分类">{menu.map((c,i)=><button key={c.name} aria-pressed={category===i} className={category===i?'active':''} onClick={()=>setCategory(i)}><span>{c.name}</span><small>{c.items.length}</small></button>)}<button className="source-button" onClick={()=>setPanel('source')}><ImageIcon size={16}/>原始价目表</button></aside>
 <section className="menu"><div className="section-heading"><div><span className="eyebrow">MENU / {String(category+1).padStart(2,'0')}</span><h2>{menu[category].name}</h2></div><span className="muted">{menu[category].items.length} 道菜</span></div><div className="dish-grid">{menu[category].items.map(d=>{const qty=cart.filter(l=>l.dish.id===d.id).reduce((s,l)=>s+l.qty,0);return <article className="dish" key={d.id}><div className="dish-top"><span className="dish-symbol">{category===3?<Leaf size={20}/>:<Flame size={20}/>}</span>{d.prices.length>1&&<span className="tag">中份 / 大份</span>}{d.pending&&<span className="pending">待核对</span>}</div><h3>{d.name}</h3><div className="dish-bottom"><div className="price"><small>¥</small>{d.prices[0]}{d.prices.length>1&&<span>起</span>}</div><button className="add" aria-label={`添加${d.name}`} onClick={()=>{if(d.prices.length>1){setSelected(d);setSize(0)}else add(d)}}>{qty>0&&<span>{qty}</span>}<Plus size={19}/></button></div></article>})}</div><p className="menu-foot">价格单位：元 · 菜名与价格按照片录入，标记项需店主确认</p></section>
 <aside className="basket"><div className="basket-title"><ShoppingBag size={20}/><h2>已选菜品</h2><span>{count} 份</span></div>{cart.length===0?<div className="empty"><ShoppingBag size={36}/><h3>先选几道喜欢的菜</h3><p>点击菜品旁的 + 加入这里</p></div>:<><div className="basket-lines">{cart.map(l=><div className="basket-line" key={`${l.dish.id}-${l.size}`}><div><strong>{l.dish.name}</strong><small>{l.dish.prices.length>1?(l.size===0?'中份':'大份'):'标准份'} · ¥{l.dish.prices[l.size]}</small></div><div className="stepper"><button aria-label={`减少${l.dish.name}`} onClick={()=>change(l.dish.id,l.size,-1)}><Minus size={14}/></button><span>{l.qty}</span><button aria-label={`增加${l.dish.name}`} onClick={()=>change(l.dish.id,l.size,1)}><Plus size={14}/></button></div></div>)}</div><label className="note-label">整单备注<textarea maxLength={200} value={note} onChange={e=>setNote(e.target.value)} placeholder="例如：少辣、不放香菜"/></label></> }<div className="basket-total"><span>合计</span><strong>¥{total}</strong></div><button className="primary" disabled={!count} onClick={()=>setPanel('cart')}>确认菜品<ArrowRight size={18}/></button><p className="basket-hint">提交后仍可继续加菜</p><button className="reference-card" onClick={()=>setPanel('source')}><img src="/menu-reference.jpg" alt="店内绿色价目表原图"/><span>照着店里的菜单点<small>查看原始价目表 →</small></span></button></aside></div></main>
 <div className="mobile-cart"><button onClick={()=>setPanel('cart')}><ShoppingBag size={22}/><span>{count} 份菜品<strong>¥{total}</strong></span></button><button className="primary" disabled={!count} onClick={()=>setPanel('cart')}>查看已选 <ArrowRight size={18}/></button></div><span className="sr-only" role="status">{message}</span>
 <Dialog open={!!selected} onOpenChange={o=>{if(!o)setSelected(null)}}><DialogContent><DialogTitle>{selected?.name}</DialogTitle><DialogDescription>选择份量后加入购物车</DialogDescription><div className="sizes">{selected?.prices.map((p,i)=><button aria-pressed={size===i} className={size===i?'chosen':''} key={i} onClick={()=>setSize(i)}>{i===0?'中份':'大份'}<strong>¥{p}</strong></button>)}</div><button className="primary" onClick={()=>{if(selected)add(selected,size);setSelected(null)}}>加入购物车</button></DialogContent></Dialog>
 <Dialog open={panel!==null} onOpenChange={o=>{if(!o)setPanel(null)}}><DialogContent className="order-dialog"><DialogTitle>{panel==='source'?'原始价目表':panel==='orders'?'01 桌 · 本桌订单':'01 桌 · 确认菜品'}</DialogTitle><DialogDescription>{panel==='source'?'以店主确认后的菜单为准。':'演示模式：仅当前页面有效，刷新后清空，不会通知厨房。'}</DialogDescription>
 {panel==='source'?<div className="dialog-scroll"><p>待核对：蘑菇拌面 ¥18、夹沙烧牛肉丸 ¥26、锅包肉烧番茄 ¥20、拌牛肉 ¥20、干锅豆角 ¥18，以及“干丝香芹菇”“韭菜银芽炒蛋”的菜名。大盘牛 / 羊肚、哨子面 / 肉丝面的具体选项也需确认。</p><img className="source-image" src="/menu-reference.jpg" alt="用户提供的完整价目表"/></div>:panel==='cart'?<><div className="dialog-scroll">{cart.length?cart.map(l=><div className="basket-line" key={`${l.dish.id}-${l.size}`}><div><strong>{l.dish.name}</strong><small>{l.dish.prices.length>1?(l.size===0?'中份':'大份'):'标准份'} · ¥{l.dish.prices[l.size]}</small></div><div className="stepper"><button aria-label={`减少${l.dish.name}`} onClick={()=>change(l.dish.id,l.size,-1)}><Minus size={14}/></button>{l.qty}<button aria-label={`增加${l.dish.name}`} onClick={()=>change(l.dish.id,l.size,1)}><Plus size={14}/></button></div></div>):<p className="empty">还没有选择菜品，先去菜单看看吧。</p>}</div><label className="note-label">整单备注<textarea maxLength={200} value={note} onChange={e=>setNote(e.target.value)} placeholder="例如：少辣、不放香菜"/></label><div className="basket-total"><span>{count} 份菜品，合计</span><strong>¥{total}</strong></div><button className="primary" disabled={!count} onClick={submit}>提交演示订单</button></>:<><div className="dialog-scroll">{!orders.length?<p className="empty">暂无订单，选好菜品后在这里查看。</p>:orders.map(o=><section className="receipt" key={o.id}><div className="receipt-heading"><strong>第 {o.id} 次点单</strong><span><Check size={14}/> 演示已提交</span></div>{o.items.map(l=><div className="receipt-line" key={`${l.dish.id}-${l.size}`}><span>{l.dish.name}{l.dish.prices.length>1?`（${l.size===0?'中份':'大份'}）`:''} × {l.qty}</span><strong>¥{l.dish.prices[l.size]*l.qty}</strong></div>)}{o.note&&<p className="muted">备注：{o.note}</p>}<div className="receipt-line"><span>本次合计</span><strong>¥{o.total}</strong></div></section>)}</div>{orders.length>0&&<div className="basket-total"><span>本桌累计 · 餐后结账</span><strong>¥{orders.reduce((s,o)=>s+o.total,0)}</strong></div>}<button className="primary" onClick={()=>setPanel(null)}>继续点菜</button></>}
 </DialogContent></Dialog></div>;
}
